version: '3'
services:
    web:
        image: nginx
        container_name: my-nginx
        ports:
            - '8080:80'
    web2:
        image: redis
        container_name: my-redis
    web3:
        image: nginx
        container_name: my-nginx2
        ports:
            - "80:80" 